name: manage-azure-policy-9f7ce29a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'definitions/policies/nsg-diag-eh_31adaa0e-2f0b-44a2-b0dc-daa88b57a8df/**'
#      - 'definitions/policies/keyvault-diag-eh_89aff399-6621-42d8-8dd2-e8ff849848de/**'
#      - 'definitions/policies/storage-account-diag-eh_31adaa0e-2f0b-44a2-b0dc-daa88b57a8d8/**'
#      - .github/workflows/manage-azure-policy-9f7ce29a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_9f7ce29a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          definitions/policies/nsg-diag-eh_31adaa0e-2f0b-44a2-b0dc-daa88b57a8df/**
          definitions/policies/keyvault-diag-eh_89aff399-6621-42d8-8dd2-e8ff849848de/**
          definitions/policies/storage-account-diag-eh_31adaa0e-2f0b-44a2-b0dc-daa88b57a8d8/**
